export enum UrlConstants {
    PERSONALITY = "/voice-assistant/personality",
    CHAT = "/voice-assistant/chat",
    MOTOR = "/motor",
    CAMERA = "/camera-settings",
    PROGRAM = "/program",
    CODE = "code",
    ASSISTANT_MODEL = "/assistant-model",
    POSE = "/pose",
    BRICKLET = "/bricklet",
    BRICKLET_PINS = "/bricklet-pins",
    HOST_IP = "/host-ip",
    RGB_BUTTON = "/button-programs",
    VOICE_SETTINGS = "/voice-assistant/voice-settings",
    LLM_SETTINGS = "/voice-assistant/llm-settings",
    VERIFY_GEMINI_KEY = "/voice-assistant/llm-settings/verify-gemini-key",
    GESTURE = "/gesture-control/gestures",
    MOVEMENT_SEQUENCE = "/gesture-control/sequences",
    JOINT_MAPPING = "/gesture-control/joint-mapping",
    MOTION_CAPTURE_SETTINGS = "/gesture-control/settings",
    VOICE_RECORDINGS = "/voice-recordings",
    LEARNING_GROUPS = "/learning-groups",
    AUTO_OFF = "/system-settings/auto-off",
    RESTART_DISPLAY = "/system-settings/restart-display",
    MENU_VISIBILITY = "/system-settings/menu-visibility",
    MOVEMENT_SETTINGS = "/movement-settings",
    FACIAL_EXPRESSIONS = "/facial-expressions",
}
