export enum UrlConstants {
    PERSONALITY = "/voice-assistant/personality",
    CHAT = "/voice-assistant/chat",
    MOTOR = "/motor",
    CAMERA = "/camera-settings",
    PROGRAM = "/program",
    CODE = "code",
    ASSISTANT_MODEL = "/assistant-model",
    POSE = "/pose",
    BRICKLET = "/bricklet",
    HOST_IP = "/host-ip",
    RGB_BUTTON = "/button-programs",
    VOICE_SETTINGS = "/voice-assistant/voice-settings",
    GESTURE = "/gesture-control/gestures",
    MOVEMENT_SEQUENCE = "/gesture-control/sequences",
}
