export enum rosServices {
    applyMotorSettings = "/apply_motor_settings",
    applyMovementSettings = "/apply_movement_settings",
    proxyRunProgramStart = "/proxy_run_program_start",
    proxyRunProgramStop = "/proxy_run_program_stop",
    getVoiceAssistantState = "/get_voice_assistant_state",
    setVoiceAssistantState = "/set_voice_assistant_state",
    getChatIsListening = "/get_chat_is_listening",
    sendChatMessage = "/send_chat_message",
    get_token_exists = "/get_token_exists",
    encryptToken = "/encrypt_token",
    decryptToken = "/decrypt_token",
    applyJointTrajectory = "/apply_joint_trajectory",
    getMicConfiguration = "/get_mic_configuration",
    setSolidStateRelayState = "/set_solid_state_relay_state",
    playAudioFromFile = "/play_audio_from_file",
    playAudioFromSpeech = "/play_audio_from_speech",
}
