export enum rosTopics {
    jointTrajectoryTopicName = "/joint_trajectory",
    motorCurrentTopicName = "/motor_current",
    cameraPreviewSizeTopicName = "/size_topic",
    cameraTimerPeriodTopicName = "/timer_period_topic",
    cameraTopicName = "/camera_topic",
    cameraQualityTopic = "/quality_factor_topic",
    chatMessages = "/chat_messages",
    voiceAssistantState = "/voice_assistant_state",
    chatIsListening = "/chat_is_listening",
    motorSettingsTopicName = "/motor_settings",
    proxyRunProgramFeedback = "/proxy_run_program_feedback",
    proxyRunProgramResult = "/proxy_run_program_result",
    proxyRunProgramStatus = "/proxy_run_program_status",
    programInput = "/program_input",
    deleteTokenTopic = "/delete_token",
    solidStateRelayState = "/solid_state_relay_state",
    gestureCaptureControl = "/gesture_capture_control",
    gestureCaptureResult = "/gesture_capture_result",
    gestureRetargetTargets = "/gesture_retarget_targets",
    browserPoseLandmarks = "/browser_pose_landmarks",
    audioStream = "/audio_stream",
}
